version: '3.8'
services:
  client:
    build: ./client
    container_name: client
    image: app:react
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app
